### ISSUE TITLE
It doesn't work for me

### ISSUE THREAD

**Issue by AdeIndraYP** [hktkqj/Aokana-Extractor#2]
Sorry im still new at programming world,

I confused how to run this. there is any video about it ?

**Comment by hktkqj** [comment]
Nope. However, I wrote an article on [https://zhuanlan.zhihu.com/p/108191499](Article)(in Chinese) that show how it works. You may install related libraries like ffmpeg&imagemagick.
You can also mail to [hktkqj@gmail.com](url) for further help.
